CREATE TABLE SAILOR
(
SID VARCHAR2 (4),
SNAME VARCHAR2 (10),
MNAME VARCHAR2 (10),
SURNAME VARCHAR2 (10),
RATING NUMBER(2),
AGE NUMBER(3,1)
);

DESC SAILOR;

ALTER TABLE SAILOR ADD PRIMARY KEY (SID);
ALTER TABLE SAILOR ADD CHECK (SID LIKE 's%');
ALTER TABLE SAILOR ADD CHECK (SNAME IN INITCAP(SNAME));
ALTER TABLE SAILOR MODIFY SURNAME VARCHAR2(10) NOT NULL;
ALTER TABLE SAILOR MODIFY RATING NUMBER(2) DEFAULT 0;
ALTER TABLE SAILOR MODIFY AGE NUMBER(3,1) NOT NULL;

VALUE INSERTION:
INSERT INTO SAILOR VALUES ('s22', 'Fredrico', NULL, 'Roberts', 7, 45 );
INSERT INTO SAILOR VALUES ('s31', 'Lubber', NULL, 'Sheen',     8, 55.5 );
INSERT INTO SAILOR VALUES ('s32', 'Charlotte', NULL, 'Gordin', 8, 25.5 );
INSERT INTO SAILOR VALUES ('s258', 'Mary', 'Beth', 'Lyon', 10, 35 );
INSERT INTO SAILOR VALUES ('s64, 'Horatio',NULL, 'Powell', 7, 35.4 );
INSERT INTO SAILOR VALUES ('s71', 'Zorba',NULL, 'Alex', 10, 16 );
INSERT INTO SAILOR VALUES ('s29', 'Brutus', NULL, 'Slatter', 1, 33.8 );
INSERT INTO SAILOR VALUES ('s95', 'Deep', 'Graceb', 'Davis', 3, 63.5);
INSERT INTO SAILOR VALUES ('s74','Horatio',NULL, 'Forrest', 9, 35);
INSERT INTO SAILOR VALUES ('s85', 'Sara', 'Art', 'Powell', 3, 25.5);
INSERT INTO SAILOR VALUES ('s80', 'Deep','Kumar', 'Kumar', 6, 17);
INSERT INTO SAILOR VALUES ('s87', 'Deep', 'Kumar', 'Jha', NULL, 51 );



CREATE TABLE BOAT
(
BID NUMBER(3),
BNAME VARCHAR2(10),
COLOR VARCHAR2(6)
);

ALTER TABLE BOAT ADD PRIMARY KEY(BID);

ALTER TABLE BOAT ADD CHECK(BNAME IN UPPER (BNAME));
ALTER TABLE BOAT ADD CHECK(COLOR IN ('red', 'green', 'blue'));
DESC BOAT;

VALUE INSERTION:
INSERT INTO BOAT VALUES (101, 'INTERLAKE', 'blue');
INSERT INTO BOAT VALUES (102, 'INTERLAKE', 'red');
INSERT INTO BOAT VALUES (103, 'CLIPPER', 'green');
INSERT INTO BOAT VALUES (104, 'MARINE', 'red');


CREATE TABLE RESERVED 
(
SID VARCHAR2(4),
BID NUMBER(3),
DAY DATE
);
ALTER TABLE RESERVED ADD FOREIGN KEY (SID) REFERENCES SAILOR (SID);
ALTER TABLE RESERVED ADD FOREIGN KEY (BID) REFERENCES BOAT (BID);
ALTER TABLE RESERVED ADD CHECK  ( DAY < DATE '2000-01-01');
ALTER TABLE RESERVED ADD PRIMARY KEY (SID,BID);

VALUE INSERTION:
INSERT INTO RESERVED VALUES ('s22', 101, '10-OCT-1998');
INSERT INTO RESERVED VALUES ('s22', 103, '10-AUG-1998');
INSERT INTO RESERVED VALUES ('s22', 102,  '10-OCT-1998');
INSERT INTO RESERVED VALUES ('s22', 104, '10-JUL-1998');

INSERT INTO RESERVED VALUES ('s31', 102, '11-OCT-1998');
INSERT INTO RESERVED VALUES ('s31', 103, '11-JUN-1998');
INSERT INTO RESERVED VALUES ('s31', 104, '11-DEC-1998');

INSERT INTO RESERVED VALUES ('s64', 101, '09-MAY-1998');
INSERT INTO RESERVED VALUES ('s64', 102, '09-AUG-1998');

INSERT INTO RESERVED VALUES ('s74', 103, '09-AUG-1998');

INSERT INTO RESERVED VALUES ('s80', 102,  '07-JUL-1998');

INSERT INTO RESERVED VALUES ('s87', 101,  '08-JUL-1998');
INSERT INTO RESERVED VALUES ('s87', 102,  '12-DEC-1998');