CREATE TABLE SAILOR
(
SID VARCHAR2 (4),
SNAME VARCHAR2 (10),
MNAME VARCHAR2 (10),
SURNAME VARCHAR2 (10),
RATING NUMBER(2),
AGE NUMBER(3,1)
);

DESC SAILOR;

ALTER TABLE SAILOR ADD PRIMARY KEY (SID);
ALTER TABLE SAILOR ADD CHECK (SID LIKE 's%');
ALTER TABLE SAILOR ADD CHECK (SNAME IN INITCAP(SNAME));
ALTER TABLE SAILOR MODIFY SURNAME VARCHAR2(10) NOT NULL;
ALTER TABLE SAILOR MODIFY RATING NUMBER(2) DEFAULT 0;
ALTER TABLE SAILOR MODIFY AGE NUMBER(3,1) NOT NULL;

VALUE INSERTION:
INSERT INTO SAILOR VALUES ('s22', 'Fredrico', NULL, 'Roberts', 7, 45 );
INSERT INTO SAILOR VALUES ('s31', 'Lubber', NULL, 'Sheen',     8, 55.5 );
INSERT INTO SAILOR VALUES ('s32', 'Charlotte', NULL, 'Gordin', 8, 25.5 );
INSERT INTO SAILOR VALUES ('s258', 'Mary', 'Beth', 'Lyon', 10, 35 );
INSERT INTO SAILOR VALUES ('s64, 'Horatio',NULL, 'Powell', 7, 35.4 );
INSERT INTO SAILOR VALUES ('s71', 'Zorba',NULL, 'Alex', 10, 16 );
INSERT INTO SAILOR VALUES ('s29', 'Brutus', NULL, 'Slatter', 1, 33.8 );
INSERT INTO SAILOR VALUES ('s95', 'Deep', 'Graceb', 'Davis', 3, 63.5);
INSERT INTO SAILOR VALUES ('s74','Horatio',NULL, 'Forrest', 9, 35);
INSERT INTO SAILOR VALUES ('s85', 'Sara', 'Art', 'Powell', 3, 25.5);
INSERT INTO SAILOR VALUES ('s80', 'Deep','Kumar', 'Kumar', 6, 17);
INSERT INTO SAILOR VALUES ('s87', 'Deep', 'Kumar', 'Jha', NULL, 51 );